[[libblastrampoline]]
arch = "aarch64"
git-tree-sha1 = "bb8a4080bbed7bb50d639dd2e504e3f3cb611be2"
os = "macos"

    [[libblastrampoline.download]]
    sha256 = "af3a95acb83fcdc21cfd890e1f6f28bae5097120aefa3f09abb0bafc6eeafa04"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.aarch64-apple-darwin.tar.gz"
[[libblastrampoline]]
arch = "aarch64"
git-tree-sha1 = "1ff510b191743597573e9748e37a55656c3db592"
libc = "glibc"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "3205a281d1d672bd2607e753f1ca7fa34cdfce53a0482debdeb5ec7265a6fe18"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.aarch64-linux-gnu.tar.gz"
[[libblastrampoline]]
arch = "aarch64"
git-tree-sha1 = "771ac13c542cc71e12034a9e71461cc3b223096e"
libc = "musl"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "f4217dafc00340297dbd231b26557ed76908f11d56a9e94f71c2c791908dd3ed"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.aarch64-linux-musl.tar.gz"
[[libblastrampoline]]
arch = "aarch64"
git-tree-sha1 = "e32a51d2074d3aec9be3bec528e0cccfa20940a7"
os = "freebsd"

    [[libblastrampoline.download]]
    sha256 = "216be80ac798b72888fea4bc9b8d73db4b10534db2b66cc8b397429200d7a3f7"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.aarch64-unknown-freebsd.tar.gz"
[[libblastrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7acfdc3ae3268117d19f9dad44a8f8207c09aa7"
libc = "glibc"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "4c3f4b1f62c12e7b81198024bde7a2d696f187973324353da3267dd5366b87e4"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.armv6l-linux-gnueabihf.tar.gz"
[[libblastrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "71de712b68d58caddaf04ba664b97c4f7eb27393"
libc = "musl"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "c40e79ee69ca5e90db28795592ad49437e1af10cbbabf5b979d0953e52e9f32f"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.armv6l-linux-musleabihf.tar.gz"
[[libblastrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bcc49c5e4f4893842c875aa4dc278917d4d70743"
libc = "glibc"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "440ada456a8c742d4ebc64689d2e69df12f622a2d5904c0ec4cedfba97c7f270"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.armv7l-linux-gnueabihf.tar.gz"
[[libblastrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e09e5df32cbd2e6c144c03de69a8432dfff999f5"
libc = "musl"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "91450795f223875107ad8734d3377a47778e69fbd1bfc58acb09ff532b269b8a"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.armv7l-linux-musleabihf.tar.gz"
[[libblastrampoline]]
arch = "i686"
git-tree-sha1 = "5605583c53e276227c6a03e860c82367f02ffe0d"
libc = "glibc"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "0b4bf2e589dcf6ed5ef01857b7c0f9901061d6f1404389888adc788b5882469e"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.i686-linux-gnu.tar.gz"
[[libblastrampoline]]
arch = "i686"
git-tree-sha1 = "e5528f1abe8fe0e8c75e8f8656515f3160f32d0d"
libc = "musl"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "f8898a14d2b03ca4af142ec4e580fe0082106b791b12a772158b6efbe38f94d6"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.i686-linux-musl.tar.gz"
[[libblastrampoline]]
arch = "i686"
git-tree-sha1 = "0ce16cba6294f5db8e794528d2a4344cfb4d74f6"
os = "windows"

    [[libblastrampoline.download]]
    sha256 = "c531df7799f0052612cc12fbc0c70e129fdafa7d8680416b93ed655daa59ca5a"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.i686-w64-mingw32.tar.gz"
[[libblastrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "c9545bd8f7df656647f8cbd946b07167f8a5529f"
libc = "glibc"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "e1b7a9d0c8809027b4b2b48fd84e02d6d8888c8d7afe3acd3b0bda93e88bd788"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.powerpc64le-linux-gnu.tar.gz"
[[libblastrampoline]]
arch = "riscv64"
git-tree-sha1 = "b4769029d9ab1ed0b3a879ef1e49fdbab723929e"
libc = "glibc"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "60424ca86c537474390a6a8532666caaceeddae0d6758caf678323a6efb1e6ba"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.riscv64-linux-gnu.tar.gz"
[[libblastrampoline]]
arch = "x86_64"
git-tree-sha1 = "722fba7099371c41558c8202d565fd13fd7ee345"
os = "macos"

    [[libblastrampoline.download]]
    sha256 = "dd29052af7b9c1d1b7150d43ef9745decff6dd1ea39a358f66e3dde595d8e412"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.x86_64-apple-darwin.tar.gz"
[[libblastrampoline]]
arch = "x86_64"
git-tree-sha1 = "53cd7dd1af728b0537f00804a570077a1afcd2cc"
libc = "glibc"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "cab05677bf29d40a794fc22af22eef6414ea5f112242279da44b39b77b604166"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.x86_64-linux-gnu.tar.gz"
[[libblastrampoline]]
arch = "x86_64"
git-tree-sha1 = "cf8ecd737ae8a1bc593f790c13754dada9a65467"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[libblastrampoline.download]]
    sha256 = "87c0f6b2afa4d8c07d461441b6af6319a20157936a19c36a66c0c201212cbc1e"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[libblastrampoline]]
arch = "x86_64"
git-tree-sha1 = "a1c2b24dbe96a0a96721b66987dce86b39b50483"
libc = "musl"
os = "linux"

    [[libblastrampoline.download]]
    sha256 = "da8984255febfd4ad717cd9a7d1cbb31a56cabcd1292682c5dee6b692c35a47d"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.x86_64-linux-musl.tar.gz"
[[libblastrampoline]]
arch = "x86_64"
git-tree-sha1 = "2917ec5e5541283421a364572623f8f725295c33"
os = "freebsd"

    [[libblastrampoline.download]]
    sha256 = "a03c315fc2c2098ac2d05477f70aceec3c917026773a5f0c13a934fb8a422495"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.x86_64-unknown-freebsd.tar.gz"
[[libblastrampoline]]
arch = "x86_64"
git-tree-sha1 = "e43c570dc143b693731cbec7c7f7306bd39ec814"
os = "windows"

    [[libblastrampoline.download]]
    sha256 = "70e6b64e9eefde7755f78011e61288a8b829a6bd051c23b8f9ebac9df8cabf65"
    url = "https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl/releases/download/libblastrampoline-v5.11.2+2/libblastrampoline.v5.11.2.x86_64-w64-mingw32.tar.gz"
